
  CREATE OR REPLACE FORCE VIEW SIMCO.VW_BUSCADOR_GENERAL (CODIGO, NOMBRE, DETALLE, TIPO) AS 
  select N_ID_ACTIVIDAD CODIGO, C_NOMACTIVIDAD NOMBRE, CASE C_TIPO WHEN 'AC' THEN 'ACONTECIMIENTO' ELSE 'ACTUACION DEFENSORIAL' END DETALLE , 1 TIPO from SIMCO.simco_reg_actividad UNION ALL SELECT N_ID_CASO, C_NOMCASO, 'CASO', 2 TIPO FROM SIMCO.SIMCO_REG_CASO WHERE C_INDVIGENTE = 'A'UNION ALL SELECT N_ID_ACTOR, C_NOMACTOR, 'ACTOR', 3 TIPO FROM SIMCO.SIMCO_REG_ACTOR;
